### ISSUE TITLE
Not compatible with TerraForged

### ISSUE THREAD

**Issue by Sam-Chai** [Someone-Else-Was-Taken/BetterNether-Reforged#14]
BetterNether-Reforged cannot generate biomes with TerraForged.
It's just only a small amount of stalactites will be generated, dont have any BetterNether's biome or entity in it.
But I use the Minecraft original generator it's generate normally.
Hope to Fix it.

Use original generator:
![image](https://user-images.githubusercontent.com/29940426/134315264-40c45bf0-70f7-4a1d-8d3e-edab6544007c.png)

Use TerraForged generator:
![image](https://user-images.githubusercontent.com/29940426/134315399-490ef6eb-c3ff-4244-beeb-0c065a0a3878.png)

**Comment by turabian-luvr** [comment]
For comparison, the betterend forge port includes a world type that you can select in the list of end generators in terraforge's config. BetterNether Reforged does not have a world type that shows up in the list for the nether.

OP: I've just tested it selecting one of the quark world types in the list is a decent workaround. I got the BetterNether biomes, mobs, etc.

**Comment by Sam-Chai** [comment]
> For comparison, the betterend forge port includes a world type that you can select in the list of end generators in terraforge's config. BetterNether Reforged does not have a world type that shows up in the list for the nether.
> 
> 
> 
> OP: I've just tested it, and selecting one of the quark world types in the list is a decent workaround. I got the BetterNether biomes, mobs, etc.
> 
> 
> 
> e: nevermind, idk if it's a problem with the quark worldtype specifically, but a quark dungeon did generate in the nether with that worldtype selected

so I only need to choose quark as the Nether generator?

the interesting is that Terraforged can choose three generators to generate three dimensions, such as, overworld use Terraforged generator, the nether use quark's, and the end use betterend's.

I will test it, thanks.

**Comment by Sam-Chai** [comment]
> For comparison, the betterend forge port includes a world type that you can select in the list of end generators in terraforge's config. BetterNether Reforged does not have a world type that shows up in the list for the nether.
> 
> OP: I've just tested it, and selecting one of the quark world types in the list is a decent workaround. I got the BetterNether biomes, mobs, etc.
> 
> e: nevermind, idk if it's a problem with the quark worldtype specifically, but a quark dungeon did generate in the nether with that worldtype selected

I tested just now. It can generate normally. Beautiful nether.
But there's another problem:
when I into a nether city, then the server console send me a error message:
`[20:54:48][ERROR/]: Unknown structure start: city`
The console sends it almost every second ...

**Comment by SpinHarmony** [comment]
I don’t know if this will fix the Nether City issue, but if you have Infernal Expansion, you can get the best results from the infernalexp:compat Nether type. I have yet to find a mod that doesn’t generate biomes in that world type.

**Comment by Murdock412k** [comment]
Okay, so I'm in the Terraforged Config, but where do yall see where to add Quark as the worldgen type?  
![image](https://user-images.githubusercontent.com/26029107/143409489-c5eea069-2b60-45f2-94c0-8e88a464c4b1.png)

**Comment by Murdock412k** [comment]
How were yall able to change it? It stays at default 
![image](https://user-images.githubusercontent.com/26029107/143411309-4335e8ec-fab3-4fa2-8de8-c29d9cabde2f.png)

**Comment by Murdock412k** [comment]
Question, how would you modify this for a server?

**Comment by Mikaaah** [comment]
> 

You create a terraforged preset in singleplayer, then hit save. This creates a file you can then upload to the server (check the terraforged wiki on how to use exported presets on servers)

**Comment by Sam-Chai** [comment]
okay. betternether latest version already solved. close this issue.
