### ISSUE TITLE
[issue] Unable to Locate any Vanilla Biomes

### ISSUE THREAD

**Issue by Shibva** [Someone-Else-Was-Taken/BetterNether-Reforged#31]
So I have been trying to locate a basalt delta and have used some other mods in atempts to try and locate it,

I think something is wrong 

before you make this issue invalid, if you need any sort of resounce just let me know, the only nether modification mods are piglin expation, betternether (this mod), and infernal expansion

**Comment by SteamDoge9000** [comment]
scratch that, the issue is back, idk why but I think something is causing the vanilla biomes to overwrite wtih these ones
