### ISSUE TITLE
1 year later. Still no updates. We're all waiting.

### ISSUE THREAD

**Issue by MagmaSlime123** [Someone-Else-Was-Taken/BetterNether-Reforged#57]

**Comment by Toma400** [comment]
1. It is no year later, it is barely few months.
2. Modders have life, they are not obliged to serve us. You should be beyond thankful that Forge port for BN exists thanks to this wonderful dude, not be demanding
3. When developing, someoneelsewastaken is making a lot of updates, so... not true.

**Comment by MagmaSlime123** [comment]
Well, it shouldn't be 5 months of waiting. A lot of us want update.

**Comment by Toma400** [comment]
Absolutly it should, if modder needs 5 months, they should wait 5 months. They are not obliged to do anything. Community can go to garbage can if they don't care about modders' health.
